<?php
    /**
     * Template path (with trailing DIRECTORY_SEPARATOR !)
     */
    define('APPLICATION_LAYOUTS_PATH', APPLICATION_DIRECTORY . DIRECTORY_SEPARATOR . 'Resources' . DIRECTORY_SEPARATOR . 'Private' . DIRECTORY_SEPARATOR . 'Layouts' . DIRECTORY_SEPARATOR);
    define('APPLICATION_TEMPLATES_PATH', APPLICATION_DIRECTORY . DIRECTORY_SEPARATOR . 'Resources' . DIRECTORY_SEPARATOR . 'Private' . DIRECTORY_SEPARATOR . 'Templates' . DIRECTORY_SEPARATOR);
    define('APPLICATION_PARTIALS_PATH', APPLICATION_DIRECTORY . DIRECTORY_SEPARATOR . 'Resources' . DIRECTORY_SEPARATOR . 'Private' . DIRECTORY_SEPARATOR . 'Partials' . DIRECTORY_SEPARATOR);
